# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/5b8ce6d9-9e7d-42ea-b4d4-c640feac68e2";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/6E3F-8CCA";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/c0313bfa-6630-450c-96e1-97aeb251cca5";
      fsType = "ext4";
    };

  fileSystems."/mnt/data1" =
    { device = "/dev/disk/by-uuid/EAFC-D22D";
      fsType = "exfat";
      options = [ "uid=1000" "gid=100" "umask=0022" "nofail" ];
    };

  fileSystems."/mnt/data2" =
    { device = "/dev/disk/by-uuid/6E7F-F22D";
      fsType = "exfat";
      options = [ "uid=1000" "gid=100" "umask=0022" "nofail" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/c07b8756-52d1-4f81-b852-3c7b1d915408"; }
    ];

  boot.resumeDevice = "/dev/disk/by-uuid/c07b8756-52d1-4f81-b852-3c7b1d915408";

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
